name: CI

on:
  push:
    branches:
      - main
      - release/*
  pull_request:
    branches:
      - main

jobs:
  php:
    name: php
    uses: Icinga/github-actions/.github/workflows/php.yml@php-workflows
    with:
      databases: false
